### ISSUE TITLE
Generate records request form that is sent to retention center

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#121]

**Comment by tom-karasch** [comment]
[RRF #05272020HW.pdf](https://github.com/gaepdit/FMS/files/10177554/RRF.05272020HW.pdf)
Example PDF file for Records Request

**Comment by tom-karasch** [comment]
Documentation for Dynamic PDF
https://www.dynamicpdf.com/examples/pdf-form-filling-in-pdf-.net-core

**Comment by patdnr** [comment]
Current filled form
[FMS_Retention_Records_export_2022-12-20-23-50-16.815.pdf](https://github.com/gaepdit/FMS/files/10274576/FMS_Retention_Records_export_2022-12-20-23-50-16.815.pdf)
