### ISSUE TITLE
Remove "Code" from FacilityType Entity and all other references

### ISSUE THREAD

**Issue by tom-karasch** [gaepdit/FMS#128]
The numeric CODE in the facility type is not used and is not necessary and needs to be removed. This includes The Entity, SeedData,  Repositories, DTOs and pages where it it referenced.

**Comment by dougwaldron** [comment]
I can take this

**Comment by tom-karasch** [comment]
Thanks. Probably makes more sense since you are already modifying the DB tables. Thanks

**Comment by dougwaldron** [comment]
FYI, I added a Description property so they can show that BROWN means "Brownfield", etc. 

It's up to you how to handle the migration. We can always edit the final values after migration.
