### ISSUE TITLE
Add email for compliance officers

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#131]
Email is already available in the personnel table and is much more reliable than matching on name. When migrating, normalize the addresses to our current format.

**Comment by dougwaldron** [comment]
I'll work on the entities & repositories. Tom, please work on the data migration.

**Comment by tom-karasch** [comment]
To be clear, are you adding an "email" column to the CO table in the new FMS DB??

**Comment by dougwaldron** [comment]
Yes
