### ISSUE TITLE
Migrate compliance officer email

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#133]
See #131

**Comment by tom-karasch** [comment]
Doug, can we get rid of the UnitId column in the ComplianceOfficer Table, when adding the email column? I don't think we are using it anywhere in the App.  As soon as you want I can change seed data, and I have the script ready to populate DEV and UAT DBs with Compliance Office data, including Email and UnitId if necessary.

**Comment by tom-karasch** [comment]
Sorry. I see that you did remove the UnitId column. Thanks

**Comment by dougwaldron** [comment]
I just deployed to dev with the email column. I'll go ahead and remove Unit ID (it's still there)

**Comment by dougwaldron** [comment]
Unit ID removed. Please go ahead and update the emails in dev. Thanks!

**Comment by tom-karasch** [comment]
OK, I have to do an update script, because I cannot do  a Drop/Create table due to key constraints.

**Comment by tom-karasch** [comment]
Completed updating the email address for Compliance Officers, with replacement to current email format of  GivenName.FamilyName@dnr.ga.gov in DEV database.
