### ISSUE TITLE
Export reports as Excel instead of CSV files

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#152]
Switch from CsvHelper to ClosedXML to export Excel files instead of CSV files on the report page

**Comment by dougwaldron** [comment]
For reference, CTS uses ClosedXML: https://github.com/search?q=repo%3Agaepdit%2Fcomplaint-tracking%20closedxml&type=code

**Comment by tom-karasch** [comment]
ClosedXML Documentation
https://closedxml.readthedocs.io/en/latest/index.html
