### ISSUE TITLE
Fix visibility of map symbols that overlap

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#155]
Facilities with identical (or close enough) lat/long will overlap and not be available to select.

Use [Marker Clustering](https://developers.google.com/maps/documentation/javascript/marker-clustering) and [OverlappingMarkerSpiderfier](https://github.com/jawj/OverlappingMarkerSpiderfier) to fix.

<details>
<summary>Screenshots</summary>

![Map-EI on top of each other](https://user-images.githubusercontent.com/737326/98548755-e4c4a300-2267-11eb-8797-72d5ef827266.JPG)
![Map-EI on top of each other-Zoom 2](https://user-images.githubusercontent.com/737326/98548756-e55d3980-2267-11eb-9b45-abd32d1b8fb4.JPG)
</details>

**Comment by dougwaldron** [comment]
Update based on comments from Jason:

| Facility     | Latitude  | Longitude  |
|--------------|-----------|------------|
| GAD981218365 | 33.475218 | -82.013595 |
| GAD981226277 | 33.475272 | -82.013743 |

Only one is visible in [a Facility Search](https://uat-fms.gaepd.org/Facilities/Map?Spec.Radius=0.25&Spec.Latitude=33.475&Spec.Longitude=-82.014&Spec.Output=1&handler=search&Spec.ShowDeleted=false#SearchResults) because they overlap

**Comment by tom-karasch** [comment]
Update has been published to UAT for testing and approval. 
https://uat-fms.gaepd.org
