### ISSUE TITLE
Facility Edit does not keep "State" when loading

### ISSUE THREAD

**Issue by tom-karasch** [gaepdit/FMS#163]
On Edit Facility page, the State defaults to Alabama instead of using the Facility's correct state.

**Comment by tom-karasch** [comment]
Doug, I am not sure how to fix this, looking at the code. It should be displaying the "Facility Model's" State value, but it is defaulting to Alabama. If I remember correctly, it was was working in the past.

**Comment by tom-karasch** [comment]
I think the "States" list needs to be changed to a "Select List" with the State Abbreviation as the Key. OR where we going to change the data in the DB to update the State abbreviations to the full state name? Was this something I forgot to do during data migration?

**Comment by dougwaldron** [comment]
Yeah, we aren't using state abbreviations. Run this script:
[FMS-data-migration/Update to correct state abbrev.sql](https://github.com/gaepdit/FMS-data-migration/blob/main/SQLScripts/Update%20or%20delete%20scripts/Update%20to%20correct%20state%20abbrev.sql)

**Comment by tom-karasch** [comment]
Thanks, I forgot I ran that on the original, but didn't do it on the final migration.
Thank You for reminding me!

**Comment by tom-karasch** [comment]
Databases corrected
