### ISSUE TITLE
Redeploy to Web App 3 server

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#165]
- [x] Create temporary subdomain for new server - Wednesday - Tom
- [x] Add SSL cert to server  - Sam
- [x] Add web deploy endpoint (sei3) to DNS - Tom
- [x] Create app in IIS on prod app 3 - Doug
- [x] Update publish profile - Wednesday - Doug
- [x] Deploy to prod app 3 server - Wednesday - Doug
- [x] Add test URL to Azure app config - Thursday - Doug
- [x] Test - Everyone
- [x] Switch DNS for primary subdomain - Friday - Tom
- [x] Test prod URL - Monday - Everyone

Cleanup:
- [x] Delete app and folder from prod app 1 server - Doug
- [x] Remove test URL from Azure - Doug

**Comment by tom-karasch** [comment]
New sub domain for testing ProdApp3 is fms-test.gaepd.org

**Comment by dougwaldron** [comment]
App moved and working. Removed from old server.
