### ISSUE TITLE
Update to .NET 6

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#191]
.NET 5.0 will reach [end of life](https://github.com/dotnet/core/blob/main/releases.md#supported-net-versions) on May 8, 2022

**Comment by dougwaldron** [comment]
@tom-karasch Please prioritize this issue when you begin work on FMS. This should be a relatively quick fix. You can examine the commits in [this pull request](https://github.com/gaepdit/enforcement-orders/pull/55) to see the steps I had to take in ENFO. It should be very similar in FMS.

**Comment by tom-karasch** [comment]
I did the following steps as per ENFO pull request:
-Update target frameworks to .NET 6
-Update NuGet packages
-Update GitHub workflow to use .NET 6

-Add TFM to the publish profiles  
I did these 4 actions as a single commit.

-Fix CodeQL GitHub action

closes #191

**Comment by tom-karasch** [comment]
Tested in Dev and works fine. Merge, close and Publish to Prod.
