### ISSUE TITLE
Migrate authentication to Microsoft Identity Web

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#218]
Copied from gaepdit/template-app#56:

> `AddAzureAD` and related methods are [marked obsolete](https://github.com/dotnet/aspnetcore/blob/e882394a7bb38930da748291fe2c2ceaa6a80588/src/Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADAuthenticationBuilderExtensions.cs#L105) and "will be removed in a future version." The "Microsoft.AspNetCore.Authentication.AzureAD.UI" package is being replaced by "[Microsoft.Identity.Web](https://aka.ms/ms-identity-web)".

See gaepdit/template-app#63 for a working fix.

**Comment by tom-karasch** [comment]
All works well. Merged and tested

**Comment by tom-karasch** [comment]
Accidentally closed this issue with the pull request. I have published this to DEV and UAT servers for review by Tamika and Maryam G.

**Comment by tom-karasch** [comment]
Tested and works well
