### ISSUE TITLE
SqlException: Error converting data type numeric to decimal. [HTTP 200 returned while handling GET Request]

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#219]
Raygun report https://app.raygun.com/crashreporting/26p0xsd/errors/162658265345 has more details about the error

**Comment by dougwaldron** [comment]
Error can be reproduced by visiting this URL: https://fms.gaepd.org/Facilities/Map?Spec.Radius=0.5&Spec.Latitude=33.791948&Spec.Longitude=-84435004&Spec.Output=1&handler=search

**Comment by tom-karasch** [comment]
Thanks, Doug. I just saw this is Raygun. I see that you entered longitude without the decimal point. I will check all input fields of this type, and fix them.
