### ISSUE TITLE
Update ClosedXML package

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#220]
[ClosedXML](https://github.com/ClosedXML/ClosedXML) just released a major update with breaking changes. Migrating to the new version is not mandatory or urgent but comes with some nice memory consumption improvements and better error handling. Plus, future ClosedXML updates will require this migration anyway.

See the [release notes](https://github.com/ClosedXML/ClosedXML/releases/tag/0.100.0) and [migration guide](https://closedxml.readthedocs.io/en/latest/migrations/migrate-to-0.100.html).

**Comment by tom-karasch** [comment]
Accidentally closed this issue after pull request review. I have published this to DEV and UAT servers for review by Tamika and Maryam G.

**Comment by tom-karasch** [comment]
Reviewed, tested and works well
