### ISSUE TITLE
Upgrade to .NET 7

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#230]
See gaepdit/EPD-IT/issues/98

**Comment by tom-karasch** [comment]
Doug, 
I was looking through your notes for this upgrade. Will you be upgrading the servers? I can attempt upgrading FMS.

**Comment by dougwaldron** [comment]
OK, go ahead. I've finished ENFO and CTS (main), so you can use those as reference if you'd like. I'll install on the servers. Right now, it's installed on dev (.67), so you'll be able to test a deployment.

**Comment by tom-karasch** [comment]
https://dev-fms.gaepd.org  published an runs correctly. I think I also made all the necessary changes for the VS Code IDE. 
Doug, please make any changes necessary that you need to run in VS Code or other IDEs. I think I found them all by going through the whole solution in VS Code, myself. But, feel free to fix any other thing I may have missed. Thanks, Tom
