### ISSUE TITLE
Switch to NSubstitute for unit test mocking

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#243]
[NSubstitute](https://github.com/nsubstitute/NSubstitute) provides a simpler syntax and also avoids a potential repeat of some recent security concerns in Moq.

**Comment by dougwaldron** [comment]
Much of this can be accomplished using carefully crafted search and replace operations.

See https://github.com/gaepdit/sbeap/pull/151 for a similar migration.

**Comment by tom-karasch** [comment]
Thanks, Doug
