### ISSUE TITLE
Create data migration scripts

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#26]

**Comment by dougwaldron** [comment]
Some additional updates needed, based on recent discussions:

- [ ] Add missing facility IDs ("Unknown", etc.) with sequential filler IDs, e.g., UNK-001
- [ ] `TRIM()` all strings before inserting

**Comment by tom-karasch** [comment]
I am making modifications as odd migrated data is found during UAT. Some require data to be modified before migration. Some issues require programmatic modifications.

**Comment by dougwaldron** [comment]
Is it time to close this issue and track remaining items in separate issues?
