### ISSUE TITLE
FMS additions in Entity Framework to modify existing DB

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#281]
Run Build of new FMS DB additions in Entity Framework to modify existing DB, and test data integrity.

**Comment by dougwaldron** [comment]
Hey @amberehall & @tom-karasch, what involvement do you need from me for this issue?

**Comment by tom-karasch** [comment]
@dougwaldron , I need to review that the new fields are in the Local DB correctly. Then I would just like you to walk with me through updating the Dev DB correctly with EF. I know it is a simple process, but I haven't done it in a while, so I would just like your eyes on it. Thanks

**Comment by dougwaldron** [comment]
Okay, sounds good! Just let me know when you want to get together and work on it.

**Comment by amberehall** [comment]
Tom K confirmed this is finished during the 1/30 status meeting
