### ISSUE TITLE
RN Properties functionality/ data

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#321]
What happens to the RN Properties if the Type is changed to a different Type when editing?  Does it just become obsolete data in the system?  Should the RN Properties still be available if it changes from RN to HSI?

**Comment by tom-karasch** [comment]
Which pages are you referring to? The RN properties remain, but become irrelevant when the type is changed.

**Comment by amberehall** [comment]
Any of the pages where that data exists... I was just thinking if someone accidentally used that RN Type and filled out the RN Properties information then realized it was wrong and changed the Type... would it be a problem having that data retained. 

Also, if an RN becomes an HSI... I guess they will enter that as a new HSI record while retaining the original RN record but using the same File Label for both.  Today, in Access, I think they use the same record, but just flag it as HSI, so it's all on the same record regardless if it is HSI or not.

Let me know if we need to discuss for clarification... gets confusing.

**Comment by tom-karasch** [comment]
In the current Access DB where it is flagged as HSI, it is not the same record. The Notification data is just notifications. The HSI number assigned to it is just a reference to what the number is, not the actually data or docs for an HSI Facility. 
So, the RN data retained in FMS is irrelevant if the Facility Type changes.

**Comment by amberehall** [comment]
Ok, thanks for the clarification.

**Comment by amberehall** [comment]
Nevermind... they will just change the type.  I am confusing myself! But what is the point of having the HSI Number in the RN Properties if it will no longer be seen once the type is changed to HSI?

**Comment by amberehall** [comment]
Received further clarification from Tom K.  RNs will remain RNs in the system.  If it later is identified as an HSI, a new entry will be added to the system as an HSI.
