### ISSUE TITLE
Facility Type Label

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#324]
This is related to Phase 1:
Edit/Search/Details uses "Type/Environmental Interest"
vs.
Add uses "Facility Type"

**Comment by tom-karasch** [comment]
Oh. Sorry, I need to keep that consistent. I will fix this along with the Layout issues.

**Comment by tom-karasch** [comment]
Fixed the Add Page to match other pages

**Comment by amberehall** [comment]
Add still has Facility Type... did you push the fix from your env to dev?

**Comment by amberehall** [comment]
The label has been modified
