### ISSUE TITLE
Data Migration - Parcels

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#325]
The Parcels info is to be concatenated with separators and added to the Location Description field.  Where is this documented?  I don't see that defined in the Notification_Access_Table_Structures doc on MS Teams

**Comment by tom-karasch** [comment]
OK. Feel free to add that note to the Notification_Access_Table_Structures doc on MS Teams. Or I can do it if you want.

**Comment by amberehall** [comment]
I added a Note to the Notification_Access_Table_Structures doc
