### ISSUE TITLE
Determination Letter Date and Received Date - allows future dates

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#326]
Future dates are currently allowed, but should only allow current date and previous dates

**Comment by tom-karasch** [comment]
Ah. I did not even think about that. I will make a constraint on the date fields. Nice catch!

**Comment by amberehall** [comment]
Contacted the RRP to find out if a change is necessary; waiting for feedback

**Comment by amberehall** [comment]
This is Jason's feedback...


![Image](https://github.com/gaepdit/FMS/assets/148375928/a929c2e6-a6b9-457a-8d5f-8613718616ce)

**Comment by tom-karasch** [comment]
OK, but as I stated before, it may or may ot be possible. I am putting this low on my priority list

**Comment by amberehall** [comment]
That's fine... it's not critical.  It is marked as a Low Priority.

**Comment by tom-karasch** [comment]
This has been addressed and fixed
