### ISSUE TITLE
SharePoint Buttons - need user friendly error messages

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#330]
I get... "Hmmm… can't reach this page" for both buttons

**Comment by tom-karasch** [comment]
Because you did not enter a valid HSI number or Notification ID. hmmmmm ;) 
BTW, I am still working on the "RN" prefix for the Notifications, so just use a number that exists, without the RN for now.

**Comment by amberehall** [comment]
How difficult is it to only show the buttons if the numbers are valid?  I looked up an HSI number, and the HSI button worked.  I had already added the "RN" to the RN number that I created yesterday before testing it, but it still isn't working.

**Comment by tom-karasch** [comment]
I will have to see. I just want to make things functional, then tighten everything to make it "User Proof". I will be doing that stuff tomorrow.

**Comment by amberehall** [comment]
Have to be sure to use numbers that have already been used and posted out on SharePoint.  Valid RN numbers can be found here: https://gets.sharepoint.com/sites/ResponseandRemediationProgram/RNs/Shared%20Documents/

After used a valid HSI and RN number both of the buttons worked.

**Comment by amberehall** [comment]
I was just thinking... instead of doing a validation on the HSI button, do the validation on the HSI number before saving it to the RN Properties when doing an add or edit for an RN

**Comment by amberehall** [comment]
Will test again after the friendly validations are complete.

**Comment by tom-karasch** [comment]
I already took care of this with this afternoon's Publish to Dev. (2/21/2024 about 3pm)

**Comment by amberehall** [comment]
Hummm... I am getting this...

![Image](https://github.com/gaepdit/FMS/assets/148375928/5518386b-5464-4c3b-b50c-a1c00fda4b13)

**Comment by tom-karasch** [comment]
Yes, because there is bad data, and also not everything is where it should be in sharepoint. If the Sharepoint links work 90% of the time, the issue is NOT coding, it is bad data or Sharepoint folder is in the wrong place.
Also, I NEED a screen shot of FMS, so I know what was shown and what you pushed. 
Make a list of Facilities that it does this. It is not an issue for GitHub. It is an issue to put in an email to the Program to sort out sharepoint and/or Access Data

**Comment by tom-karasch** [comment]
I Literally just went to dev. Opened the RN6000 facility and the button took me straight to the Sharepoint page. Are you connected to VPN?

**Comment by amberehall** [comment]
It isn't that is doesn't work at all... it works fine with valid numbers.  It's just that it gives that error page when a value isn't valid, and users will be left wondering what they did wrong.  I was thinking a custom and more user-friendly error message would be helpful.

Unless, we just want to consider it a training thing.

**Comment by tom-karasch** [comment]
I have been trying to look at some form of Website validation to help with this. That error message is the message that comes from Sharepoint, not us. It may not be possible or take too long as the user waits, just to validate, not only that the website exists, but also that the particular folder on Sharepoint exists. When this error occurs it means that the program does not have their stuff in the right place. To check every link, every time may leave the user sitting there wondering if anything is happening. I find it to be a low priority at best and possibly unnecessary. We can give them a list of what we have in the DB, so they can make sure all things match in Sharepoint. You that Tom B. and Bo N.  just did these moves one day ago. I am sure they still need to double check everything.

**Comment by amberehall** [comment]
Yeah, I know… just making an observation.  If not possible, that’s ok, but we need to make sure that is part of the training.

**Comment by amberehall** [comment]
I spoke to Tom B a good while this morning.  He really wants to make this error message a custom message... can it be modified on the SharePoint side instead of you trying to build logic on the FMS side?  He sent this link to me:
https://www.codesigned.com/blog/create-custom-error-page-sharepoint.  

Should I talk to Michael L about it to get assistance in researching it?  I don't want this to take away from all of the other work you have going on.

![Image](https://github.com/gaepdit/FMS/assets/148375928/1c88b923-3832-49f6-b45b-7c875727b2a3)

**Comment by tom-karasch** [comment]
Well, this looks pretty straight forward, but it depends on how much access we have vs. need to the root server directories of the Sharepoint server. I will have to look into this further when I have a bit more time.

**Comment by tom-karasch** [comment]
Tom Brodell has gone through and made sure everything is in Sharepoint in the correct places. 
I have addressed the logic in FMS and have corrected the URL generation in the program. Should now be resolved. 
If anyone runs into a missing page or file in Sharepoint, they should bring it to the Attention of Tom Brodell and myself.
