### ISSUE TITLE
Add Validation for HSI number entry

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#331]
Added a "-' to the HSI number, and it threw a SQL Server error; change validation errors to be user-friendly throughout pages; screenshot of the error attached

**Comment by amberehall** [comment]
[FMS_Ph2_Error_Message.docx](https://github.com/gaepdit/FMS/files/14301421/FMS_Ph2_Error_Message.docx)

**Comment by tom-karasch** [comment]
This will take a bit of time, but I have discussed it with Doug, so I am working on it. May not be all done by start of UAT, but soon after

**Comment by amberehall** [comment]
Item was closed, but the validations are still being worked on, and the "-" in the HSI number still throws the same SQL Server error it did before.


![Image](https://github.com/gaepdit/FMS/assets/148375928/74541469-2b9b-40eb-86e5-7566596b8b3d)

**Comment by tom-karasch** [comment]
This is almost meaningless to me unless you screenshot what you actually did in the UI

**Comment by tom-karasch** [comment]
All form validation errors should be grouped under ONE major task, as they will al be handled in one pull request.
Thanks

**Comment by amberehall** [comment]
If you have 1 request to handle all validations, that is fine, but I would like to keep this open, so when the validations are done, I can remember to test this specific item.  It was created under the Defect Tracking milestone not Application Coding

**Comment by tom-karasch** [comment]
Yes, but I already did a merge on this one. It is better to close it and open a new one, so I can create a new branch. I am trying to cleanup GitHub and you keep undoing what I am trying to fix here. LOL

**Comment by tom-karasch** [comment]
I am closing this issue and creating a new one

**Comment by amberehall** [comment]
Reopening; closed another one under Application Coding
