### ISSUE TITLE
Clear Form vs.  Clear Search button

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#351]
Case ID 1.5 – Comment, UI shows the Clear Form button instead of the Clear Search button. The expected result was displayed when I clicked on the Clear Form button.

**Comment by amberehall** [comment]
![Image](https://github.com/gaepdit/FMS/assets/148375928/a20c8284-21fd-48fb-bf09-4d3e7f02b1b0)

**Comment by tom-karasch** [comment]
What is the issue here?

**Comment by amberehall** [comment]
Just the button label... very minor.  Button says "Clear Form" instead of "Clear Search"

**Comment by tom-karasch** [comment]
Well, the button does both, clear the form and clear the search results. So, you want it to say "Clear Search"?

**Comment by amberehall** [comment]
Yeah, let's go with that... that's what the test script had and that is why she reported it.
