### ISSUE TITLE
File Label of None not showing for the Location Search

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#354]
None File Label is not showing for the Location Search when it does for the Facility Search.  See example below in comment with screenshots.

**Comment by amberehall** [comment]
Comparison of Facility Search vs. Location Search


![Image](https://github.com/gaepdit/FMS/assets/148375928/10ca0049-d3aa-4e19-befb-498ee7bfcb8a)



![Image](https://github.com/gaepdit/FMS/assets/148375928/a16de328-7ee8-4138-ac43-2c5d46d1db1d)

**Comment by tom-karasch** [comment]
Nice find. I will look into this next
