### ISSUE TITLE
Location Search - Strange Discrepancy

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#355]
See screenshots below... Location address searches are inconsistent.  It seems to be that the Location Search is not using the "Address" information in the search correctly

**Comment by amberehall** [comment]
Results entering an Address and Woodstock as the City
![Image](https://github.com/gaepdit/FMS/assets/148375928/bbc029e0-7878-4df8-9749-926cd965e7f0)

Results only entering Woodstock as the City – since only Woodstock is entered in the Search Criteria, the results from the screenshot above should also be in the results below.
![Image](https://github.com/gaepdit/FMS/assets/148375928/9b0f9849-0018-4479-b274-92b3c433d4f9)

**Comment by amberehall** [comment]
Another screenshot using the address Waterside Court and City Jasper... Shows Jasper results, but Waterside Court is not in any of the addresses. (tested this in prod and got the same results)
![Image](https://github.com/gaepdit/FMS/assets/148375928/ab17072a-fd32-4ba8-a768-7276788ebc6f)

Using only the address and no city... (tested this in prod and got the same results)
![Image](https://github.com/gaepdit/FMS/assets/148375928/08ac54c0-79ab-44c1-9e16-2a3f87598b56)

**Comment by tom-karasch** [comment]
No, your search criteria should not give the same results. This is not a bug. I will explain and show you if necessary

**Comment by tom-karasch** [comment]
Addressed
