### ISSUE TITLE
Location Search - Lat/ Long Required

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#367]
I get this in the Location Search... I think it must be looking for something other than 0, but that should only be on the Add/Edit pages

**Comment by amberehall** [comment]
![Image](https://github.com/gaepdit/FMS/assets/148375928/4d70c8d9-59d6-41c1-b683-13fbac69c2ca)

With Zip…
 
![Image](https://github.com/gaepdit/FMS/assets/148375928/a54e36f8-3a09-4c9d-a53f-320d35075c65)

**Comment by tom-karasch** [comment]
Fixed in new dev/UAT version
