### ISSUE TITLE
Specify required fields for facility add/edit

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#56]

**Comment by dougwaldron** [comment]
Before this can be closed, the UI needs to have labels marking which fields are required, like an asterisk on the label element.

**Comment by tom-karasch** [comment]
Added an asterisk to each required field label on the Facility Add and Edit pages. Also added a text line above the submit button on both forms that is in red text and reads:  _* denotes required field_

**Comment by tom-karasch** [comment]
Changes made and Branch merged with DEV and Pushed to GitHub.

**Comment by tom-karasch** [comment]
Corrections completed, Push Branch to GitHub

**Comment by dougwaldron** [comment]
Closed in 511bf562
