### ISSUE TITLE
Discuss how to migrate facilities labeled "UNKNOWN"

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/FMS#69]
Example: https://dev-fms.gaepd.org/Facilities/Details/fa41202a-b99c-43b3-96b8-fbcbd3c84c78

Can try to get program to update facility number if desired

**Comment by tom-karasch** [comment]
I can change the migration script but that will apply to a lot of facilities. I will make a list of the ones that will effect for the program to review. They may want to correct many before final migration.

**Comment by dougwaldron** [comment]
Interesting. Any idea of about how many are affected? I had no idea we had facilities without a facility number.

This bug prevents work on #64, but that may be moot if program is okay with missing facility numbers.

**Comment by dougwaldron** [comment]
After discussing it, it looks like the program may need the ability to create facilities without a facility number. Going to discuss with program further.

If so, we should migrate these facility numbers as `null` instead of "Unknown". We'll also need to rewrite the app to allow empty facility numbers

**Comment by dougwaldron** [comment]
While on the same topic, need to ask the program if duplicate facility numbers are okay (see #66).

**Comment by dougwaldron** [comment]
Decision: Migrate data with sequential facility numbers e.g. "Unknown-001", etc.

Disallow duplicates in code.

**Comment by dougwaldron** [comment]
Closing this issue. Remaining work tracked elsewhere:

- Migrate data with filler facility numbers: #26 
- Prevent duplicates in new facility numbers: #66
