### ISSUE TITLE
State Abbreviations needed in States Dropdown Lists

### ISSUE THREAD

**Issue by tom-karasch** [gaepdit/FMS#83]
**Abbreviation should be added to the State Name as a Key in the Key/Value Pair.**

As of now, the states are a list of complete state names, with no index. However, the data in the database uses the standard 2 letter abbreviation for each state. Therefore, any search using the state will bring back now results. 

**_Example:_** In the main search page, simply search for facilities in the state of Georgia. This should return nearly every facility in the database. However, the search only returns 3 facilities (the only ones with "Georgia" written out) and one of the facilities is a dummy example facility. 

**State Abbreviations should be added to Class "Data"** and needed editing on Search, Add, and Edit pages for facility, and if necessary, to the repositories.

**Comment by dougwaldron** [comment]
Georgia is the only state in the current data:

```sql
select distinct STATE
from hwmb.allsites;
```

Just migrate them all as "Georgia"

**Comment by tom-karasch** [comment]
OK, I will create an update script for Dev and UAT to change "GA" to "Georgia", then migrate as "Georgia" for Prod.

**Comment by tom-karasch** [comment]
Update scripts have been run and tested in DEV and UAT databases.
